@Omniwise.API_HostAddress = https://localhost:7155

###

POST {{Omniwise.API_HostAddress}}/api/identity/login
Content-Type: application/json
 
{
    "email": "martysuwukukis.admin@cats.com",
    "password": "MartysUwUKukisAdmin69!"
}
###
